apiVersion: v1
kind: Pod
# 元数据
metadata:
  name: nginx-v1
  namespace: test
  labels:
    region: sz
    version: v1
spec:
  containers:
  - name: nginx-v1 # 容器的名字 required
    image: nginx
    imagePullPolicy: IfNotPresent   # kubectl explain pod.spec.containers.imagePullPolicy: Always、 IfNotPresent、 Never
    ports:
    - name: nginx-port
      containerPort: 80 # 容器端口










