version: '3'

services:
  collector:
    image: jaegertracing/jaeger-collector
    container_name: jaeger_collector
    hostname: jaeger_collector
    restart: always
    networks:
      - net_jaeger_collector
    ports:
      - 14269
      - 14268:14268
      - 14267
      - 14250:14250
      - 9411:9411
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - COLLECTOR_ZIPKIN_HOST_PORT=9411
      - ES_SERVER_URLS=http://47.106.198.131:9200
      - ES_USERNAME=elastic
      - ES_PASSWORD=nkDzA62W8ZZA3N7ojBpc
      - LOG_LEVEL=debug
    #depends_on:
      #- elasticsearch
  agent:
    image: jaegertracing/jaeger-agent
    container_name: jaeger_agent
    hostname: jaeger_agent
    restart: always
    networks:
      - net_jaeger_agent
    environment:
      - COLLECTOR_HOST_PORT=47.106.198.131:14267
      - REPORTER_GRPC_HOST_PORT=47.106.198.131:14250
      - LOG_LEVEL=debug
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
    depends_on:
      - collector
  query:
    image: jaegertracing/jaeger-query
    container_name: jaeger_query
    hostname: jaeger_query
    restart: always
    networks:
      - net_jaeger_query
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://47.106.198.131:9200
      - ES_USERNAME=elastic
      - ES_PASSWORD=nkDzA62W8ZZA3N7ojBpc
      - LOG_LEVEL=debug
    ports:
      - 16686:16686
    #depends_on:
      #- elasticsearch
  hotrod:
    image: jaegertracing/example-hotrod:1.6
    command: all --jaeger-agent.host-port=47.106.198.131:6831
    ports:
      - 8080:8080
    depends_on:
      - agent
networks:
  net_jaeger_agent:
    driver: bridge
  net_jaeger_collector:
    driver: bridge
  net_jaeger_query:
    driver: bridge

