# 主要用于负责批量处理指定数量的 一次性任务

apiVersion: batch/v1
kind: Job
metadata:
  name: job
  namespace: dev
  labels:
    controller: job

spec:
  # 指定job需要成功运行pod的次数 默认 1
  completions: 1
  # 指定job在任意时刻应该运行pod的数量
  parallelism: 1  
  # 指定job可运行的时间限制 超过时间还未结束 系统将尝试进行终止
  activeDeadlineSeconds: 30
  # 指定job失败后可重试的次数 默认6
  backoffLimit: 6
  # 是否可以指定selector选择器 选择pod 默认false
  manualSelector: true
  selector:
    matchLabels:
      app: nginx-pod
    matchExpressions:
      - {key: app, operator: In, values: [nginx-pod]}
  # 当副本数量不足的时候, 会根据模板文件创建pod副本
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.1
        ports:
        - containerPort: 80