# 保证一定数量的pod能够正常运行,一旦pod发生故障就会重启或者重建
# 支持对pod的数量进行扩缩容 和 版本镜像的升级

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs
  namespace: dev
  labels:
    controller: ReplicaSet

spec:
  # 副本数量
  replicas: 3  
  selector:
    matchLabels:
      app: nginx-pod
    matchExpressions:
      - {key: app, operator: In, values: [nginx-pod]}
  # 当副本数量不足的时候, 会根据模板文件创建pod副本
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.1
        ports:
        - containerPort: 80