apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dm-set
  namespace: dev
  labels:
    controller: dm-set

spec:
  selector:
    matchLabels:
      app: nginx-pod
    matchExpressions:
      - {key: app, operator: In, values: [nginx-pod]}
  # 当副本数量不足的时候, 会根据模板文件创建pod副本
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.1
        ports:
        - containerPort: 80

