version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.7.0
    container_name: elasticsearch
    hostname: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    expose:
      - 9200
    networks:
      - net_elasticsearch
    volumes:
      - /usr/local/src/elasticsearch/data:/usr/share/elasticsearch/data
      - /usr/local/src/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  kibana:
    image: kibana:7.7.0
    container_name: kibana
    hostname: kibana
    restart: always
    ports:
      - 5601:5601
    networks:
      - net_kibana
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - elasticsearch.hosts=http://172.16.0.78:9200 #设置访问elasticsearch的地址
    volumes:
      - /usr/local/src/kibana/config:/usr/share/kibana/config #配置文件挂载
networks:
  net_elasticsearch:
    driver: bridge
  net_kibana:
    driver: bridge