version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - net_nginx
    volumes:
      - /usr/local/src/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /usr/local/src/nginx/conf.d:/etc/nginx/conf.d
      - /usr/local/src/nginx/log:/var/log/nginx
      - /usr/local/src/nginx/html:/usr/share/nginx/html
networks:
  net_nginx:
    driver: bridge