version: '3'

services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - net_redis
    volumes:
      - /usr/local/src/redis/conf/redis.conf:/etc/redis.conf:rw #数据文件(redis.conf先定义才可)
      - /usr/local/src/redis/data:/data:rw #数据文件
    command:
      redis-server /etc/redis.conf --appendonly yes
networks:
  net_redis:
    driver: bridge